{
 "title": "MolokoBlogEngine",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "GET requests count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming GET/\n | stats count() by bin(1m)",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "GET requests logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming GET/\n | parse @message 'Incoming *' as res\n | display res",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "POST requests count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming POST/\n | stats count() by bin(1m)",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "POST requests logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming POST/\n | parse @message 'Incoming *' as res\n | display res",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "DELETE requests count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming DELETE/\n | stats count() by bin(1m)",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "DELETE requests logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming DELETE/\n | parse @message 'Incoming *' as res\n | display res",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "PUT requests count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming PUT/\n | stats count() by bin(1m)",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "PUT requests logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming PUT/\n | parse @message 'Incoming *' as res\n | display res",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "most frequent resources",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming/\n | parse @message 'request to * from' as path\n | stats count() by path",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "path" ]
    }
   ]
  },
  {
   "title": "most frequent user-agents",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming/\n | parse @message 'user-agent: [*]' as ua\n | stats count() by ua",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "ua" ]
    }
   ]
  },
  {
   "title": "most frequent IPs",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message\n | filter @message like /Incoming/\n | parse @message 'from * user-agent' as ip\n | stats count() by ip",
     "logGroupNames": [ "moloko" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "ip" ]
    }
   ]
  }
 ]
}