name: Check backend

on:
  push:
    branches: [ "main" ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ "main" ]
    paths: [ 'backend/**' ]

defaults:
  run:
    working-directory: ./backend

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Check format, linter, tests and coverage
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: check
